image: mhart/alpine-node

pipelines:
  default:
    - step:
        name: Save Key
        script:
          - echo $OPS_KEY_ENC | base64 -d > SERVERKEY
          - chmod 400 SERVERKEY
        artifacts:
          - SERVERKEY

    - step:
        name: Install dependencies, build and deploy
        caches:
          - node
        script:
          - yarn install
          - yarn build
        artifacts:
          - build

    - step:
        name: Deploy to server
        deployment: production
        script:
          - apk add openssh
          - scp -r -i SERVERKEY -o StrictHostKeyChecking=no ./build ops@url.ojaswa.com:/var/www/hn-newspaper/