image: mhart/alpine-node

pipelines:
  default:
    - step:
        name: Save Key
        script:
          - echo $OPS_KEY_ENC | base64 -d > $HOME/KEY
          - chmod 400 $HOME/KEY
        artifacts:
          - $HOME/KEY

    - step:
        name: Install dependencies, build and deploy
        caches:
          - node
        script:
          - yarn install
          - yarn build
        artifacts:
          - ./build

    - step:
        name: Deploy to server
        script:
          - apk add openssh
          - scp -r -i "$HOME/KEY" -o StrictHostKeyChecking=no ./build ops@url.ojaswa.com:/var/www/hn-newspaper/